/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers'
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from './common'

export type TokenPermitStruct = {
  addr: AddressLike
  amount: BigNumberish
  deadline: BigNumberish
  signature: BytesLike
}

export type TokenPermitStructOutput = [
  addr: string,
  amount: bigint,
  deadline: bigint,
  signature: string,
] & { addr: string; amount: bigint; deadline: bigint; signature: string }

export type TokenStruct = { addr: AddressLike; amount: BigNumberish }

export type TokenStructOutput = [addr: string, amount: bigint] & {
  addr: string
  amount: bigint
}

export interface LiquidityManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | 'balances'
      | 'deposit(address,(address,uint256,uint256,bytes))'
      | 'deposit(address,(address,uint256))'
      | 'deposit((address,uint256,uint256,bytes))'
      | 'deposit((address,uint256))'
      | 'deposit()'
      | 'deposit(address)'
      | 'withdraw(address,(address,uint256))'
      | 'withdraw((address,uint256))',
  ): FunctionFragment

  encodeFunctionData(
    functionFragment: 'balances',
    values: [AddressLike, AddressLike],
  ): string
  encodeFunctionData(
    functionFragment: 'deposit(address,(address,uint256,uint256,bytes))',
    values: [AddressLike, TokenPermitStruct],
  ): string
  encodeFunctionData(
    functionFragment: 'deposit(address,(address,uint256))',
    values: [AddressLike, TokenStruct],
  ): string
  encodeFunctionData(
    functionFragment: 'deposit((address,uint256,uint256,bytes))',
    values: [TokenPermitStruct],
  ): string
  encodeFunctionData(
    functionFragment: 'deposit((address,uint256))',
    values: [TokenStruct],
  ): string
  encodeFunctionData(functionFragment: 'deposit()', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'deposit(address)',
    values: [AddressLike],
  ): string
  encodeFunctionData(
    functionFragment: 'withdraw(address,(address,uint256))',
    values: [AddressLike, TokenStruct],
  ): string
  encodeFunctionData(
    functionFragment: 'withdraw((address,uint256))',
    values: [TokenStruct],
  ): string

  decodeFunctionResult(functionFragment: 'balances', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'deposit(address,(address,uint256,uint256,bytes))',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'deposit(address,(address,uint256))',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'deposit((address,uint256,uint256,bytes))',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'deposit((address,uint256))',
    data: BytesLike,
  ): Result
  decodeFunctionResult(functionFragment: 'deposit()', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'deposit(address)',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'withdraw(address,(address,uint256))',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'withdraw((address,uint256))',
    data: BytesLike,
  ): Result
}

export interface LiquidityManager extends BaseContract {
  connect(runner?: ContractRunner | null): BaseContract
  attach(addressOrName: AddressLike): this
  deployed(): Promise<this>

  interface: LiquidityManagerInterface

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>

  balances: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    'view'
  >

  'deposit(address,(address,uint256,uint256,bytes))': TypedContractMethod<
    [_depositor: AddressLike, _token: TokenPermitStruct],
    [void],
    'nonpayable'
  >

  'deposit(address,(address,uint256))': TypedContractMethod<
    [_depositor: AddressLike, _token: TokenStruct],
    [void],
    'nonpayable'
  >

  'deposit((address,uint256,uint256,bytes))': TypedContractMethod<
    [_token: TokenPermitStruct],
    [void],
    'nonpayable'
  >

  'deposit((address,uint256))': TypedContractMethod<
    [_token: TokenStruct],
    [void],
    'nonpayable'
  >

  'deposit()': TypedContractMethod<[], [void], 'payable'>

  'deposit(address)': TypedContractMethod<
    [_depositor: AddressLike],
    [void],
    'payable'
  >

  'withdraw(address,(address,uint256))': TypedContractMethod<
    [_receiver: AddressLike, _token: TokenStruct],
    [void],
    'nonpayable'
  >

  'withdraw((address,uint256))': TypedContractMethod<
    [_token: TokenStruct],
    [void],
    'nonpayable'
  >

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T

  getFunction(
    nameOrSignature: 'balances',
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    'view'
  >
  getFunction(
    nameOrSignature: 'deposit(address,(address,uint256,uint256,bytes))',
  ): TypedContractMethod<
    [_depositor: AddressLike, _token: TokenPermitStruct],
    [void],
    'nonpayable'
  >
  getFunction(
    nameOrSignature: 'deposit(address,(address,uint256))',
  ): TypedContractMethod<
    [_depositor: AddressLike, _token: TokenStruct],
    [void],
    'nonpayable'
  >
  getFunction(
    nameOrSignature: 'deposit((address,uint256,uint256,bytes))',
  ): TypedContractMethod<[_token: TokenPermitStruct], [void], 'nonpayable'>
  getFunction(
    nameOrSignature: 'deposit((address,uint256))',
  ): TypedContractMethod<[_token: TokenStruct], [void], 'nonpayable'>
  getFunction(
    nameOrSignature: 'deposit()',
  ): TypedContractMethod<[], [void], 'payable'>
  getFunction(
    nameOrSignature: 'deposit(address)',
  ): TypedContractMethod<[_depositor: AddressLike], [void], 'payable'>
  getFunction(
    nameOrSignature: 'withdraw(address,(address,uint256))',
  ): TypedContractMethod<
    [_receiver: AddressLike, _token: TokenStruct],
    [void],
    'nonpayable'
  >
  getFunction(
    nameOrSignature: 'withdraw((address,uint256))',
  ): TypedContractMethod<[_token: TokenStruct], [void], 'nonpayable'>

  filters: {}
}
